### ISSUE TITLE
!info and !whale

### ISSUE THREAD

**Issue by haxxus** [Abolah/Coinbot#1]
Hello, great tool! 

ive found issues with !info tells me not found , I guess is supposed to be !help ? 

and !whale ,  when the given amount of btc is not met it returns 'css' , should it say something else like ' no order for x amount found ' 
![general - discord_21](https://user-images.githubusercontent.com/24307265/33861012-8189e304-dea9-11e7-8f6a-67e6aaf7666c.jpg)

**Comment by Abolah** [comment]
Hello, 
Thanks for liking this tool.
The !info is deprecated. the new command is !infos

For the whale Issue I know about this and I need to do some error management coding. 

Don't hesitate to reach out if you have another issues/question

**Comment by haxxus** [comment]
Great i will continue testing/learning this tool tomorrow.

**Comment by Abolah** [comment]
The issue is solved. 
The bug appeared when the amount asked was too high.

Thank you for reaching out.
