### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by haxxus** [Abolah/Coinbot#2]
Looking great, Maybe possible to add a Now playing or rather Now watching bot status with a live btc value ? Would be very helpful

![image](https://user-images.githubusercontent.com/24307265/34080162-a8a1e510-e307-11e7-8501-877c4d724b9a.png)

**Comment by Abolah** [comment]
Heyo,
I could try to add it you're right.
I need to figure out how to do it in python tho.

Thanks

**Comment by Abolah** [comment]
I added the feature.

**Comment by haxxus** [comment]
question, how can I allow it on selected channels  ? I tried to use 

`channel = "392438553612648449, 39243855361235355"`

as an example but I get error

` Destination must be Channel, PrivateChannel, User, or Object. Received str`

is it possible ?

**Comment by Abolah** [comment]
"392438553612648449, 39243855361235355" this is a string object. 
I think the right way to try it would be:
channel1 = 392438553612648449
channel2 = 39243855361235355

Don't use the double quotes

**Comment by haxxus** [comment]
seems not :( same error .

**Comment by haxxus** [comment]
or I could possible do it by the use of discord roles placing the bot under a role allowed only by the specific channel

**Comment by Abolah** [comment]
This would be the easiest way to do it

**Comment by haxxus** [comment]
here is another suggestion , I saw another public bot use it and its graph somehow shows resistance line,  but couldn't find it anywhere public so this is the one public I found 
https://github.com/flamingYawn/discryptord

Might be useful to include a graph, maybe with the !all chart

And also the btc value under the bot icon to rotate with euro value every x seconds :)

**Comment by Abolah** [comment]
Fun Fact : I tried once to make CoinBot display charts (without any resistance lines or tools) but the processing power needed was too high and it took most of the time more than a minute to display the chart. 

This is indeed a good Idea but I'll need to completely multi thread the bot first (which is the next big target).
I'll add a RoadMap.md file to show what I want to do with the bot.

I think it would be easier to ask some website to auto draw a chart then display it on Discord than making the bot draw charts itself. Or maybe with a server with 20 CPU and 64 Go of RAM ^^.

**Comment by haxxus** [comment]
aha yes, I will look around I'm sure some api possibly creates a chart, but scraping a chart also works

**Comment by haxxus** [comment]
Abolah is it possible to edit the format of !help section ? Like adding spaces in between each section and change the top that says No Categories , if so where?

**Comment by Abolah** [comment]
Heyo
Sorry for the late answer.

It is possible but this is not my priority atm.

Cya

**Comment by haxxus** [comment]
Has the BTC value ticker been fixed on new updates ? because on old one 1.7 seems is stuck on one value

**Comment by Abolah** [comment]
Yes, The btx value is now regularly changing. Update the bot on your side

**Comment by haxxus** [comment]
Great, this could be helpful , Have the btc price switch from USD to euro value every x seconds .


Update: on my end the btc ticker value gets stuck on the first value it loads , seems it doesn't refresh

**Comment by Abolah** [comment]
ATM the btc price is displayed in USD, I'll change it later to display € aswell.
The value refresh every 10 sec normally.

**Comment by Abolah** [comment]
Yo, I changes the Timer function. The value now changes every 10 sec. On discord there may be some delay to display this information (I don't know what is the delay) If you put a print (price_in_usd) at the end of the btcgame() function it will show you the price changing.

Next step is adding the value in €

**Comment by haxxus** [comment]
Hey Abolah :) been a wile ive updated , getting this error on start .


```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "main.py", line 35, in on_ready
    await aioclient.post(url, data=payload, headers=headers)
NameError: name 'url' is not defined
```

**Comment by Abolah** [comment]
Heyo. First of all did you update to the last version ?

**Comment by haxxus** [comment]
Yes , i think i worked it , needed dbl token info

**Comment by Abolah** [comment]
dbl token is only used in my case because the bot is listed here : 
https://discordbots.org/bot/367061304042586124
In my test setup I don't put any dbl token and it still works.
The error you're getting tells that the url var (defined line 15) is not defined (which is weird)
![image](https://user-images.githubusercontent.com/10921309/37040506-4d0c80b6-215a-11e8-8b55-b2f424b9f3c1.png)

**Comment by Abolah** [comment]
closing due to gitlab moving.
New Issue thread here : https://gitlab.com/Abolah/Coinbot/issues
