### ISSUE TITLE
!all /  string indices must be integers

### ISSUE THREAD

**Issue by haxxus** [Abolah/Coinbot#3]
Getting this error on new 1.9 with !all 

string indices must be integers
mc err 'int' object is not subscriptable
err cmc 'int' object is not subscriptable
err main_finex 'int' object is not subscriptable
err main_cryptopia 'NoneType' object is not subscriptable
err main_polo 'BTC_LMC'
err main_binance 'int' object is not subscriptable

Shows partially some information but a few missing items

**Comment by haxxus** [comment]
Maybe is discord network problem , this morning seems to work .

**Comment by Abolah** [comment]
This error Happens when the api servers or discord are slow.
Issue closed
